[project]
name = "aasist-uv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.2.6",
    "soundfile>=0.13.1",
    "tensorboard>=2.19.0",
    "torch>=1.6.0",
    "torchcontrib>=0.0.2",
]
